### ISSUE TITLE
Split Code Into Document and Pages To Make UI A View of A Model

### ISSUE THREAD

**Issue by leighwoltman** [leighwoltman/PDF-Scanning-App#1]
I checked in an initial pass at starting to partition the code into a concept of a document and pages. One thing we have to decide is does the order of the pages in the document belong with the document, or is that just a UI concept and then when we tell a document to save, we tell it what order to save in. I'm not sure which one I like. Right now there is a lot of linkage between the UI and document for ordering, we might get rid of a lot of that linkage.

**Comment by tocaner** [comment]
I have been looking at the UI yesterday. But I think if we first break some of the linkage with the UI, it will be easier to work on different UI ideas.

So maybe I am going to work on that first

**Comment by leighwoltman** [comment]
Sounds good, I think my initial seperation (it isn't perfect) of the code into Document and Page class helps with that. 

What do you think? Should the document with the 'Pages' have a concept of page order, or should the UI tell it what order to output them in?

**Comment by tocaner** [comment]
Hi Leigh,

Document class certainly helps with decoupling UI from the rest.

I did not understand your question exactly about the page ordering. But do you think that:
- Document keeps the ordering of the pages.
- UI commands ask the document to change the order.
- The pages on the UI view are displayed based on the order in the Documents.
- Save command does not have to specify the page order
- Can we save a range of pages? or Print pages from, to?

**Comment by leighwoltman** [comment]
I think that is one option. I think it probably makes sense to go forward with that. I think the other option is for the document to be an unordered list and the UI to pass an order in which to save, but the way you described it is probably the best way to start.

Definitely save ranges would make sense. Could be a future item from my standpoint, but I know you use that feature.

**Comment by tocaner** [comment]
I am not sure about the Document idea now. It seems like we are keeping two lists, one in UI representation and the other is the Documents class. Each item in UI has the tag assigned to a Page. We are repeating each operation in two places: move up Page in document, move up component index in UI. Delete Page in document, do the same in UI, etc. 

Maybe document should not have a list. Manipulate pages in UI. Then make a List<Page> and pass it to the Document function. For example:

ButtonSaveClick()
{
  List<Page> pages = GetPagesFromUI();
  Document.Save(pages);
}

Any thoughts on that?

**Comment by leighwoltman** [comment]
I agree it would be easier, but I think it would make better separation if the document existed as an ordered list. I was thinking that the Page being a Tag could go away, and maybe we could avoid the duplication by having the UI make a call to the Document that says "do something to page at index X". Then the document could do this and give a event back to the UI that would say, refresh index X and Y.

Thoughts?

**Comment by tocaner** [comment]
So an example:
- After scan UI calls document.addpage(Page);
- document raises OnPageInserted(sender, args { index } )
- UI then has an event handler where it inserts Document.Pages[index].Thumbnail to its view  at index location.

Another example:
- On UI User selects an item and presses delete.
- UI calls document.removepage(item.index)
- document raises OnPageDeleted(sender, args { index })
- UI then on the event handler removes item at index location

Another example:
- On UI User selects an item and moves it to another index.
- UI calls document.move(old_index, new_index);
- document raises OnPageMoved(sender, args { old_index, new_index })
- UI then on the event handler relocates the item on the view

**Comment by leighwoltman** [comment]
Sounds great to me. Really seems like we would be following a model view approach with our model being the document and the view being the UI.

**Comment by tocaner** [comment]
Hi Leigh,

Just made a significant check-in to the app. Added events to the document like we discussed. MainForm code has a lot of changes. You may want to update to last version before making any changes.

**Comment by leighwoltman** [comment]
I took a quick look at these changes and they look great!
