### ISSUE TITLE
PdfImport cannot import files created by Primo PDF

### ISSUE THREAD

**Issue by tocaner** [leighwoltman/PDF-Scanning-App#12]
[2015-11-04 Corolla Service.pdf](https://github.com/leighwoltman/PDF-Scanning-App/files/168269/2015-11-04.Corolla.Service.pdf)

**Comment by leighwoltman** [comment]
Taking a quick look at this, the document is opened by the PDF Importer. It finds 3 pages. On each page it looks like it finds ~9 images, but instead of being listed as JPEG encoded "/DCTDecode", they are listed as "/CCITTFaxDecode" encoded (for the filter field).

**Comment by leighwoltman** [comment]
This article appears to give some promising examples particularily the 2nd answer down.

http://stackoverflow.com/questions/2641770/extracting-image-from-pdf-with-ccittfaxdecode-filter

**Comment by leighwoltman** [comment]
For interest, it appears the reason this format was chosen is likely because Caner typically scans in black and white:

https://en.wikipedia.org/wiki/Group_4_compression

**Comment by tocaner** [comment]
I actually also tracked it this much...

Caner Tosuner
tocaner@gmail.com
(902) 832-6619
(902) 483-2829 cell/work
21 Loon Terrace
Bedford, Nova Scotia
B4A 3X9

**Comment by tocaner** [comment]
I am sure I am not the only one in the world.

Caner Tosuner
tocaner@gmail.com
(902) 832-6619
(902) 483-2829 cell/work
21 Loon Terrace
Bedford, Nova Scotia
B4A 3X9

**Comment by leighwoltman** [comment]
The current code imports the images it finds, but the images are encoded in small strips which would need to be pieced back together - 0c8a385509d12c2c0499c5a1bffaf639b8294d78

**Comment by leighwoltman** [comment]
Currently, importing these files is done via PDF import which preserves the original page. This doesn't allow one to resample or edit the output, but we will eventually add the option to rasterize any page if one wants to do this type of editing.

Commited as e70ede79984994709758fdd324ce66c18eebd6c8
