### ISSUE TITLE
Drag and drop in WPF is broken

### ISSUE THREAD

**Issue by leighwoltman** [leighwoltman/PDF-Scanning-App#15]
With the new UI in WPF has broken drag and drop. Likely we should be using the WPF version of ListView instead of a Windows Forms Host container hosting the WinForms version.

**Comment by leighwoltman** [comment]
Drag and drop is somewhat function in the WPF version. However, the insertion mark doesn't show up and when you drop and image it always falls to the index 0 location (because it is using the location of the insertion mark to drop to)

**Comment by tocaner** [comment]
Working like a charm...
