### ISSUE TITLE
Add width/height settings to Scanning

### ISSUE THREAD

**Issue by tocaner** [leighwoltman/PDF-Scanning-App#9]
Wia code already supports this, Twain code needs to be written to access the driver for these settings.

**Comment by leighwoltman** [comment]
@tocaner, I think you've standardized this already?

**Comment by leighwoltman** [comment]
Notice in WindowMain.xaml.cs we have code:

settings.PageType = pageType;
      settings.CustomScanArea = new BoundsInches(0, 0, fAppSettings.CustomPageSize.Width, fAppSettings.CustomPageSize.Height);

I don't think we should have this concept of PageType, we should just be passing in a custom size every time. We can make Letter, Legal, etc concepts of the UI.
